#! /bin/sh -e
DEBIAN_FRONTEND=noninteractive
. /usr/share/debconf/confmodule

vals=`ip link show | egrep '^[^  ]' | cut -d: -f2 | cut -c2- | tr "\\n" " " | sed 's/ /, /g'  | sed 's/, $//'`
echo "Select options: $vals"

db_subst question/select vals "$vals"

db_set question/select "$val"
echo "Select value set to: $val"

db_get question/select
echo "Select value: $RET"

db_input critical question/select || [ $? -eq 30 ]
db_go

db_get question/select
echo "Select value after input: $RET"